/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    A: typeof import('./src/components/a.vue')['default']
    A_mitt: typeof import('./src/components/a_mitt.vue')['default']
    B: typeof import('./src/components/b.vue')['default']
    B_mitt: typeof import('./src/components/b_mitt.vue')['default']
    BoxTrans: typeof import('./src/components/box-trans.vue')['default']
    C: typeof import('./src/components/c.vue')['default']
    Dialog: typeof import('./src/components/Dialog/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    Form: typeof import('./src/components/form.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Loading: typeof import('./src/components/Loading/index.vue')['default']
    ProvideA: typeof import('./src/components/provideA.vue')['default']
    ProvideB: typeof import('./src/components/provideB.vue')['default']
    RelA: typeof import('./src/components/relA.vue')['default']
    RelB: typeof import('./src/components/relB.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('./src/components/skeleton.vue')['default']
    Sync: typeof import('./src/components/sync.vue')['default']
    Tabs: typeof import('./src/components/tabs.vue')['default']
    TransGroup: typeof import('./src/components/trans-group.vue')['default']
    VModel: typeof import('./src/components/v-model.vue')['default']
  }
}

// For TSX support
declare global {
  const A: typeof import('./src/components/a.vue')['default']
  const A_mitt: typeof import('./src/components/a_mitt.vue')['default']
  const B: typeof import('./src/components/b.vue')['default']
  const B_mitt: typeof import('./src/components/b_mitt.vue')['default']
  const BoxTrans: typeof import('./src/components/box-trans.vue')['default']
  const C: typeof import('./src/components/c.vue')['default']
  const Dialog: typeof import('./src/components/Dialog/index.vue')['default']
  const ElAside: typeof import('element-plus/es')['ElAside']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCard: typeof import('element-plus/es')['ElCard']
  const ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
  const ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
  const ElCol: typeof import('element-plus/es')['ElCol']
  const ElContainer: typeof import('element-plus/es')['ElContainer']
  const ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
  const ElForm: typeof import('element-plus/es')['ElForm']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElHeader: typeof import('element-plus/es')['ElHeader']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElMain: typeof import('element-plus/es')['ElMain']
  const ElMenu: typeof import('element-plus/es')['ElMenu']
  const ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
  const ElOption: typeof import('element-plus/es')['ElOption']
  const ElRadio: typeof import('element-plus/es')['ElRadio']
  const ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
  const ElSelect: typeof import('element-plus/es')['ElSelect']
  const ElSwitch: typeof import('element-plus/es')['ElSwitch']
  const ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
  const Form: typeof import('./src/components/form.vue')['default']
  const HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  const Loading: typeof import('./src/components/Loading/index.vue')['default']
  const ProvideA: typeof import('./src/components/provideA.vue')['default']
  const ProvideB: typeof import('./src/components/provideB.vue')['default']
  const RelA: typeof import('./src/components/relA.vue')['default']
  const RelB: typeof import('./src/components/relB.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Skeleton: typeof import('./src/components/skeleton.vue')['default']
  const Sync: typeof import('./src/components/sync.vue')['default']
  const Tabs: typeof import('./src/components/tabs.vue')['default']
  const TransGroup: typeof import('./src/components/trans-group.vue')['default']
  const VModel: typeof import('./src/components/v-model.vue')['default']
}